version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: 12
    commands:
      - echo install stage
      - npm install
  pre_build:
    commands:   
      - echo pre build phase
  build:
    commands: 
      - echo build
      - npm run build
  post_build:
    commands:  
      - echo post build
      - npm run start:prod